### ISSUE TITLE
MENGUBAH DEST KODE DAN KODE POS DI KODE TOKO 061425

### ISSUE THREAD

**Issue by Evan2403** [Evan2403/ok#2]
Dear Team IT,

Mohon dibantu untuk merubah dest kode dan kode pos di toko 061425 :

Sebelumnya : 
Kode Pos : 12950
Dest Kode : 011504

Sebenarnya : 
Kode Pos : 40911
Dest Kode : 020481

Terima Kasih

**Comment by Andri1907** [comment]
dear tim it, mohon dibantu pengajuanini

terima kasih
